### ISSUE TITLE
Support Pageres 5.0.*

### ISSUE THREAD

**Issue by drybjed** [marius-wieschollek/passwords#150]
### System Information
- Nextcloud Version: 15
- PHP Version: 7.3
- Passwords Version: 2019.5.0
- Browser and Version: `pageres` 5.0.0
- Client OS and Version: does not apply
- Server OS and Version: Debian Stretch, 9.9

### Steps to reproduce
1. Create new password
2. Check the password details, wait for the website preview

The `pageres` command expects either an URL with `https://` prefix, or a filename to render an image. Currently the function in the `lib/Helper/Preview/PageresCliHelper.php` file executes the `pageres` command with only the domain, for example `example.com`, without the `https://` protocol string, which results in `pageres` trying to find the `/tmp/example.com` file and failing.

Modifying the https://github.com/marius-wieschollek/passwords/blob/master/src/lib/Helper/Preview/PageresCliHelper.php#L41 line from
```php
        $domain   = escapeshellarg($domain);
```
to
```php
        $domain   = 'https://'.escapeshellarg($domain);
```
results in a working state, but this is only a hack and I'm sure there's a saner way to do this.

### Actual result

The website previews are not generated properly.

### Expected result

The website previews should be generated after a short while.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"wuMlZwxWtwbzUGKdaVBg","level":3,"time":"2019-05-26T22:44:24+02:00","remoteAddr":"::ffff:153.19.230.209","user":"drybjed","app":"passwords","method":"GET","url":"/index.php/apps/passwords/api/1.0/service/preview/mail.com/desktop/640/360...","message":{"Exception":"Exception","Message":"Pageres Error\nCommand: cd /tmp/ && /usr/local/bin/pageres 'mail.com' 1366x768 --user-agent='Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0' --delay=4 --filename='5ceafaa61d005' --overwrite 2>&1\nOutput: Error: net::ERR_FILE_NOT_FOUND at file:///tmp/mail.com \n    at navigate (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/FrameManager.js:121:37) \n    at <anonymous> \n    at process._tickCallback (internal/process/next_tick.js:189:7) \n  -- ASYNC -- \n    at Frame.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/helper.js:110:27) \n    at Page.goto (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Page.js:629:49) \n    at Page.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/helper.js:111:23) \n    at captureWebsite (/usr/local/share/.config/yarn/global/node_modules/capture-website/index.js:145:13) \n    at <anonymous> \n    at process._tickCallback (internal/process/next_tick.js:189:7)\n","Code":0,"Trace":[{"file":"/srv/www/nextcloud/apps/passwords/lib/Helper/Preview/AbstractPreviewHelper.php","line":92,"function":"getPreviewData","class":"OCA\\Passwords\\Helper\\Preview\\PageresCliHelper","type":"->","args":["'mail.com'","desktop"]},{"file":"/srv/www/nextcloud/apps/passwords/lib/Services/WebsitePreviewService.php","line":125,"function":"getPreview","class":"OCA\\Passwords\\Helper\\Preview\\AbstractPreviewHelper","type":"->","args":["mail.com","desktop"]},{"file":"/srv/www/nextcloud/apps/passwords/lib/Services/WebsitePreviewService.php","line":101,"function":"getWebsitePreview","class":"OCA\\Passwords\\Services\\WebsitePreviewService","type":"->","args":["mail.com","desktop","pageres_mail.com_desktop_640x360_640x0.jpg",640,360,640,0]},{"file":"/srv/www/nextcloud/apps/passwords/lib/Controller/Api/ServiceApiController.php","line":201,"function":"getPreview","class":"OCA\\Passwords\\Services\\WebsitePreviewService","type":"->","args":["mail.com","desktop",640,360,640,0]},{"file":"/srv/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"getPreview","class":"OCA\\Passwords\\Controller\\Api\\ServiceApiController","type":"->","args":["mail.com","desktop","640","360..."]},{"file":"/srv/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\Api\\ServiceApiController"},"getPreview"]},{"file":"/srv/www/nextcloud/lib/private/AppFramework/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\Api\\ServiceApiController"},"getPreview"]},{"file":"/srv/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["ServiceApiController","getPreview",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"domain":"mail.com","view":"desktop","width":"640","height":"360...","_route":"passwords.service_api.get_preview"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"domain":"mail.com","view":"desktop","width":"640","height":"360...","_route":"passwords.service_api.get_preview"}]},{"file":"/srv/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"domain":"mail.com","view":"desktop","width":"640","height":"360...","_route":"passwords.service_api.get_preview"}]},{"file":"/srv/www/nextcloud/lib/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/passwords/api/1.0/service/preview/mail.com/desktop/640/360..."]},{"file":"/srv/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/srv/www/nextcloud/apps/passwords/lib/Helper/Preview/PageresCliHelper.php","Line":64,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36","version":"15.0.8.1","id":"5ceb00119f365"}
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Press F12, copy what you see
```
</details>

**Comment by marius-wieschollek** [comment]
The Pageres Preview support was built for version 4.1.*. I guess that Pageres 5.* does this differently. I will check this and see how support can be added.

**Comment by marius-wieschollek** [comment]
Pageres 5 should be supported with the current nightly version and the upcoming 2019.7 version. 

You can install nightlies by enabling `Show Nightly Updates in "Apps"` in the admin settings.
