### ISSUE TITLE
Website-Previews aren't being created correctly

### ISSUE THREAD

**Issue by neurolag** [marius-wieschollek/passwords#293]
### System Information
- Nextcloud Version: 
- PHP Version: 7.4.9
- Database and Version: 19.0.2
- Passwords Version: 2020.8.0
- Browser and Version: Edge 85.0.564.44
- Client OS and Version: Windows 10 2004
- Server OS and Version: Docker

### Steps to reproduce
1. Install pageres using `npm`
2. Set preview-service to `Pageres/PhantomJS`

### Expected result
Screenshots should be generated

### Actual result
Log-messages occurr which point out that `$domain` in `getPreviewData`-calls actually doesn't contain the domain but rather the whole url.

This issue might or might not cause issues for following website-preview helpers, too:
- `ScreenlyHelper`  
  Cause of this statement:  
  https://github.com/marius-wieschollek/passwords/blob/7e877eb7b826cc664127b2faf07dbe9102fac6f8/src/lib/Helper/Preview/ScreeenlyHelper.php#L90-L94 Notice, that the request to screenly would be looking like this: `http://https://sonos.com`
- `ScreenShotLayer`  
  https://github.com/marius-wieschollek/passwords/blob/7e877eb7b826cc664127b2faf07dbe9102fac6f8/src/lib/Helper/Preview/ScreenShotLayerHelper.php#L33-L41 as `http://` is prepended

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```json
{
    "reqId": "bbgJWJvuhZb4ZSd3c0eo",
    "level": 3,
    "time": "2020-09-03T20:15:55+00:00",
    "remoteAddr": "192.168.32.1",
    "user": "manuth",
    "app": "passwords",
    "method": "GET",
    "url": "/index.php/apps/passwords/api/1.0/service/preview/www.sonos.com/desktop/640/360...",
    "message": {
        "Exception": "Exception",
        "Message": "Pageres Error\nCommand: cd /tmp/ && /usr/bin/pageres 'http://'\\''https://www.sonos.com'\\''' 1366x768 --user-agent='Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0' --delay=4 --filename='5f514efa048b5' --overwrite 2>&1\nOutput: Error: Failed to launch chrome! \n/usr/lib/node_modules/pageres-cli/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory \n \n \nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md \n \n    at onClose (/usr/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/Launcher.js:348:14) \n    at Interface.<anonymous> (/usr/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/Launcher.js:337:50) \n    at Interface.emit (events.js:326:22) \n    at Interface.close (readline.js:424:8) \n    at Socket.onend (readline.js:202:10) \n    at Socket.emit (events.js:326:22) \n    at endReadableNT (_stream_readable.js:1244:12) \n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/html/custom_apps/passwords/lib/Helper/Preview/PageresCliHelper.php",
                "line": 65,
                "function": "getPreviewData",
                "class": "OCA\\Passwords\\Helper\\Preview\\PageresCliHelper",
                "type": "->",
                "args": [
                    "'http://'\\''https://www.sonos.com'\\'''",
                    "desktop",
                    "http"
                ]
            },
            {
                "file": "/var/www/html/custom_apps/passwords/lib/Helper/Preview/AbstractPreviewHelper.php",
                "line": 92,
                "function": "getPreviewData",
                "class": "OCA\\Passwords\\Helper\\Preview\\PageresCliHelper",
                "type": "->",
                "args": [
                    "'https://www.sonos.com'",
                    "desktop"
                ]
            },
            {
                "file": "/var/www/html/custom_apps/passwords/lib/Services/WebsitePreviewService.php",
                "line": 125,
                "function": "getPreview",
                "class": "OCA\\Passwords\\Helper\\Preview\\AbstractPreviewHelper",
                "type": "->",
                "args": [
                    "www.sonos.com",
                    "desktop"
                ]
            },
            {
                "file": "/var/www/html/custom_apps/passwords/lib/Services/WebsitePreviewService.php",
                "line": 101,
                "function": "getWebsitePreview",
                "class": "OCA\\Passwords\\Services\\WebsitePreviewService",
                "type": "->",
                "args": [
                    "www.sonos.com",
                    "desktop",
                    "pageres_www.sonos.com_desktop_640x360_640x0.jpg",
                    640,
                    360,
                    640,
                    0
                ]
            },
            {
                "file": "/var/www/html/custom_apps/passwords/lib/Controller/Api/ServiceApiController.php",
                "line": 203,
                "function": "getPreview",
                "class": "OCA\\Passwords\\Services\\WebsitePreviewService",
                "type": "->",
                "args": [
                    "www.sonos.com",
                    "desktop",
                    640,
                    360,
                    640,
                    0
                ]
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 170,
                "function": "getPreview",
                "class": "OCA\\Passwords\\Controller\\Api\\ServiceApiController",
                "type": "->",
                "args": [
                    "www.sonos.com",
                    "desktop",
                    "640",
                    "360..."
                ]
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 100,
                "function": "executeController",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Passwords\\Controller\\Api\\ServiceApiController"
                    },
                    "getPreview"
                ]
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/App.php",
                "line": 137,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Passwords\\Controller\\Api\\ServiceApiController"
                    },
                    "getPreview"
                ]
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php",
                "line": 47,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::",
                "args": [
                    "ServiceApiController",
                    "getPreview",
                    {
                        "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
                    },
                    {
                        "domain": "www.sonos.com",
                        "view": "desktop",
                        "width": "640",
                        "height": "360...",
                        "_route": "passwords.service_api.get_preview"
                    }
                ]
            },
            {
                "function": "__invoke",
                "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
                "type": "->",
                "args": [
                    {
                        "domain": "www.sonos.com",
                        "view": "desktop",
                        "width": "640",
                        "height": "360...",
                        "_route": "passwords.service_api.get_preview"
                    }
                ]
            },
            {
                "file": "/var/www/html/lib/private/Route/Router.php",
                "line": 297,
                "function": "call_user_func",
                "args": [
                    {
                        "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
                    },
                    {
                        "domain": "www.sonos.com",
                        "view": "desktop",
                        "width": "640",
                        "height": "360...",
                        "_route": "passwords.service_api.get_preview"
                    }
                ]
            },
            {
                "file": "/var/www/html/lib/base.php",
                "line": 1012,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->",
                "args": [
                    "/apps/passwords/api/1.0/service/preview/www.sonos.com/desktop/640/360..."
                ]
            },
            {
                "file": "/var/www/html/index.php",
                "line": 37,
                "function": "handleRequest",
                "class": "OC",
                "type": "::",
                "args": []
            }
        ],
        "File": "/var/www/html/custom_apps/passwords/lib/Helper/Preview/PageresCliHelper.php",
        "Line": 67,
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.44",
    "version": "19.0.2.2",
    "id": "5f5168339b844"
}
```

As seen in the logs, at somepoint the domain `sonos.com` gets transformed into `'https://sonos.com'`, and though I was trying very hard to find the code where this happens, I was not able to find it.

**Comment by marius-wieschollek** [comment]
I think the issue is less severe and only affects the http fallback option of the pageres preview service. There the domain is incorrectly overwritten with the complete url. You can try the [nightly](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Use-Nightlies) to check if the fix works for you.

**Comment by neurolag** [comment]
Awesome, using the nightly build did the trick!
Thanks for the quick fix 🎉
