### ISSUE TITLE
Call to undefined method OCA\Passwords\Migration\CheckAppRequirements::canUpgradeFromPreviousVersion()

### ISSUE THREAD

**Issue by syssi** [marius-wieschollek/passwords#387]
### System Information
**Server:**
```json
 Run "php ./occ passwords:system:report debug" in your Nextcloud install directory and put the output here
 or fill out the fields below

 Nextcloud Version: 20.0.8.1
 PHP Version: 7.4.18
 Database and Version: MariaDB 10.4.19
 Server OS and Version: Debian Buster
 Passwords Version: 2021.6.0-build4141
```

**Client:**
```
 Browser and Version: doesn't matter here
 Client OS and Version: doesn't matter here
```

### Steps to reproduce

```
$ php occ app:enable passwords
An unhandled exception has been thrown:
Error: Call to undefined method OCA\Passwords\Migration\CheckAppRequirements::canUpgradeFromPreviousVersion() in /var/nextcloud/apps/passwords/lib/Migration/CheckAppRequirements.php:63
Stack trace:
#0 /var/nextcloud/lib/private/Repair.php(112): OCA\Passwords\Migration\CheckAppRequirements->run(Object(OC\Repair))
#1 /var/nextcloud/lib/private/legacy/OC_App.php(1042): OC\Repair->run()
#2 /var/nextcloud/lib/private/Installer.php(145): OC_App::executeRepairSteps('passwords', Array)
#3 /var/nextcloud/core/Command/App/Enable.php(123): OC\Installer->installApp('passwords', false)
#4 /var/nextcloud/core/Command/App/Enable.php(93): OC\Core\Command\App\Enable->enableApp('passwords', Array, false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/nextcloud/occ(11): require_once('/var/nextcloud/...')
#12 {main}
```

### Expected result

No exception.

### Actual result

Passwords cannot be enabled.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
```
</details>

**Comment by marius-wieschollek** [comment]
Thanks for letting me know. This should be fixed again with 2021.6.0-build4146 .
