### ISSUE TITLE
Export Error Cannot read properties of null (reading 'value')

### ISSUE THREAD

**Issue by erwin-frohsinn** [marius-wieschollek/passwords#485]
### System Information
**Server:**
```json
{
    "version": {
        "server": "23.0.2.1",
        "app": "2022.2.12",
        "lsr": true,
        "php": "7.4.3",
        "cronPhp": "7.4.3"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}

```

**Client:**
```
Browser: Brave [Version 1.35.103 Chromium: 98.0.4758.102 (Offizieller Build) (64-Bit)](https://brave.com/latest/)
Firefox shows the same result
Kubuntu 21.04
```

### Steps to reproduce
1. Klicked "Sichern und Wiederherstellen" (Safe and restore)
2. Format: Vordefiniertes CSV (predefined CSV)
3. Optionen "Passwörter exportieren" (Export Passwords)
4. Klicked "Exportieren" (Export)

### Expected result
CSV should be generated

### Actual result
Popup-Window "Export Fehler
Cannot read properties of null (reading 'value')"
Button changes to "läuft..." (Running...") and doesn't finish
### Nextcloud log
No Entries regarding Password app found

</details>

### Browser log
<details>
<summary>Browser log</summary>

```
BackupSection.7f41fa8a41b70d620350.js:1 TypeError: Cannot read properties of null (reading 'value')
    at Function._convertCustomFieldsForExport (/apps/passwords/js/Static/ExportManager.2573a8a8fa4fa37f5c2f.js:1:5250)
    at Function._convertObjectToExportArray (/apps/passwords/js/Static/ExportManager.2573a8a8fa4fa37f5c2f.js:1:4991)
    at d._convertDbToExportArray (/apps/passwords/js/Static/ExportManager.2573a8a8fa4fa37f5c2f.js:1:4192)
    at async d.exportCsv (/apps/passwords/js/Static/ExportManager.2573a8a8fa4fa37f5c2f.js:1:1602)
    at async d.exportDatabase (/apps/passwords/js/Static/ExportManager.2573a8a8fa4fa37f5c2f.js:1:452)
(anonymous) @ BackupSection.7f41fa8a41b70d620350.js:1
```
</details>

**Comment by marius-wieschollek** [comment]
I have pushed a nightly release which should fix this. It would be great if you can test it.

**Comment by erwin-frohsinn** [comment]
Thanks for your prompt reaction and sorry for my delayed answer. To my regret, the testing of a nightly release would probably go over my technical capabilities.
