### ISSUE TITLE
ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) HelperService.php:117

### ISSUE THREAD

**Issue by patricksebastien** [marius-wieschollek/passwords#496]
### System Information
**Server:**
```
 Nextcloud Version: 23.0.3
 PHP Version: 8.0
 Database and Version: Mysql
 Server OS and Version: Linux
 Passwords Version: 2022-03-20
```

### Steps to reproduce
I am not able to run any occ command, for example:
occ passwords:system:report debug

```
An unhandled exception has been thrown:
ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /.../nextcloud/app/apps/passwords/lib/Services/HelperService.php:117
Stack trace:
#0 /.../nextcloud/app/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 [internal function]: spl_autoload_call()
#3 /.../nextcloud/app/lib/private/AppFramework/Utility/SimpleContainer.php(112): ReflectionClass->__construct()
...
```

**Comment by patricksebastien** [comment]
Oups was using PHP 7.4..... sorry for the noise. Closing.
