### ISSUE TITLE
php occ commands fails if passwords app is enabled

### ISSUE THREAD

**Issue by compumatter** [marius-wieschollek/passwords#575]
### System Information
**Server:**
```json
 Run "php ./occ passwords:system:report debug" in your Nextcloud install directory and put the output here
 or fill out the fields below

sudo -u www-data php occ passwords:system:report debug
An unhandled exception has been thrown:
ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /SM_DATA/web_cloud/public_html/apps/passwords/lib/Services/HelperService.php:117
Stack trace:
#0 /SM_DATA/web_cloud/public_html/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 [internal function]: spl_autoload_call()

 Nextcloud Version: 25.0.3
 PHP Version: 8.1
 Database and Version: MariaDB 10.6.7
 Server OS and Version: Linux / Ubuntu 22.04 
 Passwords Version: 2023.1.23
```

**Client:**
```
 Browser and Version:  NC occ command line issue
 Client OS and Version: NC occ command line issue
```

### Steps to reproduce
1. Navigate via terminal to the root location of the Nextcloud installation
2. Type any occ command including but not limited to:
sudo -u www-data php occ passwords:system:report debug
sudo -u www-data php occ ldap:show-config
or any other occ command including just:  sudo -u www-data php occ

### Expected result
The result of the occ command requested

### Actual result
What does happen?
I receive a specific error that says: ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /SM_DATA/web_cloud/public_html/apps/passwords/lib/Services/HelperService.php:117

Here is the complete error:
```
An unhandled exception has been thrown:
ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /SM_DATA/web_cloud/public_html/apps/passwords/lib/Services/HelperService.php:117
Stack trace:
#0 /SM_DATA/web_cloud/public_html/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 [internal function]: spl_autoload_call()
#3 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(114): ReflectionClass->__construct()
#4 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#6 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(437): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\AppFramework\DependencyInjection\DIContainer->query()
#8 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#9 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map()
#10 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass()
#11 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#12 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#13 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(437): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#14 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\AppFramework\DependencyInjection\DIContainer->query()
#15 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#16 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map()
#17 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass()
#18 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#19 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#20 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(437): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#21 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\AppFramework\DependencyInjection\DIContainer->query()
#22 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#23 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map()
#24 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass()
#25 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#26 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#27 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(437): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#28 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\AppFramework\DependencyInjection\DIContainer->query()
#29 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#30 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map()
#31 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass()
#32 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#33 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#34 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(437): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#35 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\AppFramework\DependencyInjection\DIContainer->query()
#36 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#37 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map()
#38 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass()
#39 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#40 /SM_DATA/web_cloud/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#41 /SM_DATA/web_cloud/public_html/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#42 /SM_DATA/web_cloud/public_html/lib/private/Console/Application.php(219): OC\ServerContainer->query()
#43 /SM_DATA/web_cloud/public_html/lib/private/Console/Application.php(130): OC\Console\Application->loadCommandsFromInfoXml()
#44 /SM_DATA/web_cloud/public_html/console.php(99): OC\Console\Application->loadCommands()
#45 /SM_DATA/web_cloud/public_html/occ(11): require_once('/SM_DATA/web_cl...')
```

### Nextcloud log
<details>
<summary>Nextcloud log</summary>
I cleared the log prior to running the command.  Nothing was put in the log file.  It was still empty, after running the occ command.

```
 - Open the Nextcloud admin settings
 - Open the "Log" section
 - Click the "Copy" icon, then "Copy Raw"
```
</details>

**NOTE: If I disable the passwords app, the error goes away and occ commands behave as expected.**

**Comment by marius-wieschollek** [comment]
Run `php -v` to check which version of PHP you're using on the command line. It's not PHP 8.1.
