### ISSUE TITLE
[BUG]: Can not index "undefined" as "text"  2024.9.20 on NC30

### ISSUE THREAD

**Issue by humberg** [marius-wieschollek/passwords#681]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "30.0.1.2",
        "app": "2024.9.20",
        "lsr": false,
        "php": "8.2.23",
        "cronPhp": "8.2.24"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: Chrome 130.0.6723.71
Client OS and Version: Win10 

### Bug description

Start Chrome
Go to Website with Password
After a few seconds the Password Sign is active - I can use Passwords

....
Working 
....

I open a new Tab in Chrome
Go to (same) Website
The Password Sign tells me "No Passwords"
I open Passwords - Discover - refresh my Server
Wait
I can use Passwords for 2..3 minutes

--

Chrome - AddOn - Debug:
 Can not index "undefined" as "text"

{
  "details": {
    "data": {
      "level": "warning"
    },
    "message": "Can not index \"undefined\" as \"text\"",
    "stack": "Error: Can not index \"undefined\" as \"text\"\n    at Object.warning (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:815085)\n    at g.addFieldValue (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:917278)\n    at l._indexUrl (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:919216)\n    at l._createIndex (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:918244)\n    at l.indexItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:918051)\n    at p.add (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:919935)\n    at Object._addItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929826)\n    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929103\n    at Array.forEach (<anonymous>)\n    at Object.add (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929085)",
    "time": 1730275813884
  },
  "error": {
    "name": "Error",
    "stack": [
      "Error: Can not index \"undefined\" as \"text\"",
      "    at Object.warning (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:815085)",
      "    at g.addFieldValue (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:917278)",
      "    at l._indexUrl (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:919216)",
      "    at l._createIndex (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:918244)",
      "    at l.indexItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:918051)",
      "    at p.add (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:919935)",
      "    at Object._addItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929826)",
      "    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929103",
      "    at Array.forEach (<anonymous>)",
      "    at Object.add (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929085)"
    ],
    "string": "Error: Can not index \"undefined\" as \"text\"",
    "message": "Can not index \"undefined\" as \"text\""
  }
}

### Steps to reproduce

see below

### Expected behavior

see below

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by humberg** [comment]
Please close jdpoccorie - this is a hacked account.

**Comment by marius-wieschollek** [comment]
I will check the issue over the weekend.

I have removed the malicious comment from the hacked account. Do not open the link and do not follow the instructions on the page he posted. If you did, check your pc for viruses.

**Comment by marius-wieschollek** [comment]
From what i can see, this issue is related to the browser extension and not the nextcloud app.

I will therefore move the ticket.
