### ISSUE TITLE
Web-UI issue with NC 13.0.6. and user-key-based encryption

### ISSUE THREAD

**Issue by chrsch** [marius-wieschollek/passwords#84]
### System Information
- Nextcloud Version: 13.0.6
- PHP Version: 7.1.5
- Passwords Version: 2018.6.3
- Browser and Version: Chrome 69.0, FF 62.03
- Client OS and Version: OSX High Sierra 
- Server OS and Version: Debian 8
- **Logs**: See foldable at end

### Steps to reproduce
1. Create a new Nextcloud 13.0.6
2. Enable user-key-based encryption (remember from NC 13 on master-key-encryption is default). Therefore insert into preference table below setting before running occ encryption:enable command:
```INSERT INTO appconfig (appid, configkey, configvalue) VALUES ('encryption', 'useMasterKey',0);```
3. Login to Nextcloud for first time (after enabling encryption)
4. Check Files app etc. is working fine
5. Switch to Passwords app
6. Switch back to Files app (error will appear your keys are not initialized..)

### Actual result
Error message show, Nextcloud UI no longer works, user need to re-login to nextcloud in order to gain access to files again

### Expected result
No error should happen, user just can switch to Passwords app and back to Files app without issues

<details><summary>nextcloud.log (only above steps go to Passwords app and back to Files app)</summary>
```{"reqId":"VmlCW1CeWBnmN3T7UCZ8","level":2,"time":"2018-10-09T16:08:24+02:00","remoteAddr":"172.17.0.1","user":"test","app":"no app in context","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/folder\/show","message":"Could not decrypt the private key from user \"test\"\" during login. Assume password change on the user back-end. Error message: Bad Signature","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/69.0.3497.100 Safari\/537.36","version":"13.0.6.1"}
{"reqId":"xz6GhVB98H0gurR7gjQT","level":3,"time":"2018-10-09T16:08:25+02:00","remoteAddr":"172.17.0.1","user":"test","app":"no app in context","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/settings\/get","message":"Exception: {\"Exception\":\"OC\\\\ForbiddenException\",\"Message\":\"This request is not allowed to access the filesystem\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Files\\\/View.php(1148): OC\\\\Lockdown\\\\Filesystem\\\\NullStorage->mkdir('files_encryptio...')\\n#1 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Files\\\/View.php(267): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/test\\\/files_enc...', Array)\\n#2 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(372): OC\\\\Files\\\\View->mkdir('\\\/test\\\/files_enc...')\\n#3 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(232): OC\\\\Encryption\\\\Keys\\\\Storage->keySetPreparation('\\\/test\\\/files_enc...')\\n#4 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(117): OC\\\\Encryption\\\\Keys\\\\Storage->setKey('\\\/test\\\/files_enc...', '-----BEGIN PUBL...')\\n#5 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/KeyManager.php(298): OC\\\\Encryption\\\\Keys\\\\Storage->setUserKey('test', 'publicKey', '-----BEGIN PUBL...', 'OC_DEFAULT_MODU...')\\n#6 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/KeyManager.php(257): OCA\\\\Encryption\\\\KeyManager->setPublicKey('test', '-----BEGIN PUBL...')\\n#7 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/Users\\\/Setup.php(77): OCA\\\\Encryption\\\\KeyManager->storeKeyPair(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/Hooks\\\/UserHooks.php(180): OCA\\\\Encryption\\\\Users\\\\Setup->setupUser(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/legacy\\\/hook.php(106): OCA\\\\Encryption\\\\Hooks\\\\UserHooks->login(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Server.php(398): OC_Hook::emit('OC_User', 'post_login', Array)\\n#11 [internal function]: OC\\\\Server->OC\\\\{closure}(*** sensitive parameters replaced ***)\\n#12 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Hooks\\\/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)\\n#13 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Hooks\\\/PublicEmitter.php(36): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'postLogin', Array)\\n#14 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(368): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'postLogin', Array)\\n#15 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(605): OC\\\\User\\\\Session->completeLogin(*** sensitive parameters replaced ***)\\n#16 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(333): OC\\\\User\\\\Session->loginWithToken(*** sensitive parameters replaced ***)\\n#17 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(411): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#18 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(525): OC\\\\User\\\\Session->logClientIn(*** sensitive parameters replaced ***)\\n#19 \\\/var\\\/localhost\\\/test\\\/lib\\\/base.php(1053): OC\\\\User\\\\Session->tryBasicAuthLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request), Object(OC\\\\Security\\\\Bruteforce\\\\Throttler))\\n#20 \\\/var\\\/localhost\\\/test\\\/lib\\\/base.php(988): OC::handleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n#21 \\\/var\\\/localhost\\\/test\\\/index.php(42): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Lockdown\\\/Filesystem\\\/NullStorage.php\",\"Line\":42}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/69.0.3497.100 Safari\/537.36","version":"13.0.6.1"}
{"reqId":"xz6GhVB98H0gurR7gjQT","level":3,"time":"2018-10-09T16:08:26+02:00","remoteAddr":"172.17.0.1","user":"test","app":"no app in context","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/settings\/get","message":"Exception: {\"Exception\":\"OC\\\\ForbiddenException\",\"Message\":\"This request is not allowed to access the filesystem\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Files\\\/View.php(1148): OC\\\\Lockdown\\\\Filesystem\\\\NullStorage->mkdir('files_encryptio...')\\n#1 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Files\\\/View.php(267): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/test\\\/files_enc...', Array)\\n#2 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(372): OC\\\\Files\\\\View->mkdir('\\\/test\\\/files_enc...')\\n#3 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(232): OC\\\\Encryption\\\\Keys\\\\Storage->keySetPreparation('\\\/test\\\/files_enc...')\\n#4 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(117): OC\\\\Encryption\\\\Keys\\\\Storage->setKey('\\\/test\\\/files_enc...', '-----BEGIN PUBL...')\\n#5 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/KeyManager.php(298): OC\\\\Encryption\\\\Keys\\\\Storage->setUserKey('test', 'publicKey', '-----BEGIN PUBL...', 'OC_DEFAULT_MODU...')\\n#6 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/KeyManager.php(257): OCA\\\\Encryption\\\\KeyManager->setPublicKey('test', '-----BEGIN PUBL...')\\n#7 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/Users\\\/Setup.php(77): OCA\\\\Encryption\\\\KeyManager->storeKeyPair(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/Hooks\\\/UserHooks.php(180): OCA\\\\Encryption\\\\Users\\\\Setup->setupUser(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/legacy\\\/hook.php(106): OCA\\\\Encryption\\\\Hooks\\\\UserHooks->login(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Server.php(398): OC_Hook::emit('OC_User', 'post_login', Array)\\n#11 [internal function]: OC\\\\Server->OC\\\\{closure}(*** sensitive parameters replaced ***)\\n#12 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Hooks\\\/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)\\n#13 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Hooks\\\/PublicEmitter.php(36): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'postLogin', Array)\\n#14 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(368): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'postLogin', Array)\\n#15 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(605): OC\\\\User\\\\Session->completeLogin(*** sensitive parameters replaced ***)\\n#16 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(333): OC\\\\User\\\\Session->loginWithToken(*** sensitive parameters replaced ***)\\n#17 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(411): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#18 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/Security\\\/CORSMiddleware.php(93): OC\\\\User\\\\Session->logClientIn(*** sensitive parameters replaced ***)\\n#19 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/MiddlewareDispatcher.php(94): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\CORSMiddleware->beforeController(Object(OCA\\\\Passwords\\\\Controller\\\\Api\\\\SettingsApiController), 'get')\\n#20 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\Passwords\\\\Controller\\\\Api\\\\SettingsApiController), 'get')\\n#21 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Passwords\\\\Controller\\\\Api\\\\SettingsApiController), 'get')\\n#22 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('SettingsApiCont...', 'get', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#23 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#24 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#25 \\\/var\\\/localhost\\\/test\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/passwords...')\\n#26 \\\/var\\\/localhost\\\/test\\\/index.php(42): OC::handleRequest()\\n#27 {main}\",\"File\":\"\\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Lockdown\\\/Filesystem\\\/NullStorage.php\",\"Line\":42}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/69.0.3497.100 Safari\/537.36","version":"13.0.6.1"}
{"reqId":"JMgET6dRuNTfD4dGR3a0","level":3,"time":"2018-10-09T16:08:26+02:00","remoteAddr":"172.17.0.1","user":"test","app":"no app in context","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/settings\/get","message":"Exception: {\"Exception\":\"OC\\\\ForbiddenException\",\"Message\":\"This request is not allowed to access the filesystem\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Files\\\/View.php(1148): OC\\\\Lockdown\\\\Filesystem\\\\NullStorage->mkdir('files_encryptio...')\\n#1 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Files\\\/View.php(267): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/test\\\/files_enc...', Array)\\n#2 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(372): OC\\\\Files\\\\View->mkdir('\\\/test\\\/files_enc...')\\n#3 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(232): OC\\\\Encryption\\\\Keys\\\\Storage->keySetPreparation('\\\/test\\\/files_enc...')\\n#4 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(117): OC\\\\Encryption\\\\Keys\\\\Storage->setKey('\\\/test\\\/files_enc...', '-----BEGIN PUBL...')\\n#5 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/KeyManager.php(298): OC\\\\Encryption\\\\Keys\\\\Storage->setUserKey('test', 'publicKey', '-----BEGIN PUBL...', 'OC_DEFAULT_MODU...')\\n#6 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/KeyManager.php(257): OCA\\\\Encryption\\\\KeyManager->setPublicKey('test', '-----BEGIN PUBL...')\\n#7 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/Users\\\/Setup.php(77): OCA\\\\Encryption\\\\KeyManager->storeKeyPair(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/localhost\\\/test\\\/apps\\\/encryption\\\/lib\\\/Hooks\\\/UserHooks.php(180): OCA\\\\Encryption\\\\Users\\\\Setup->setupUser(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/legacy\\\/hook.php(106): OCA\\\\Encryption\\\\Hooks\\\\UserHooks->login(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Server.php(398): OC_Hook::emit('OC_User', 'post_login', Array)\\n#11 [internal function]: OC\\\\Server->OC\\\\{closure}(*** sensitive parameters replaced ***)\\n#12 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Hooks\\\/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)\\n#13 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Hooks\\\/PublicEmitter.php(36): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'postLogin', Array)\\n#14 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(368): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'postLogin', Array)\\n#15 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(605): OC\\\\User\\\\Session->completeLogin(*** sensitive parameters replaced ***)\\n#16 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(333): OC\\\\User\\\\Session->loginWithToken(*** sensitive parameters replaced ***)\\n#17 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/User\\\/Session.php(411): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#18 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/Security\\\/CORSMiddleware.php(93): OC\\\\User\\\\Session->logClientIn(*** sensitive parameters replaced ***)\\n#19 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/MiddlewareDispatcher.php(94): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\CORSMiddleware->beforeController(Object(OCA\\\\Passwords\\\\Controller\\\\Api\\\\SettingsApiController), 'get')\\n#20 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\Passwords\\\\Controller\\\\Api\\\\SettingsApiController), 'get')\\n#21 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Passwords\\\\Controller\\\\Api\\\\SettingsApiController), 'get')\\n#22 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('SettingsApiCont...', 'get', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#23 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#24 \\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#25 \\\/var\\\/localhost\\\/test\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/passwords...')\\n#26 \\\/var\\\/localhost\\\/test\\\/index.php(42): OC::handleRequest()\\n#27 {main}\",\"File\":\"\\\/var\\\/localhost\\\/test\\\/lib\\\/private\\\/Lockdown\\\/Filesystem\\\/NullStorage.php\",\"Line\":42}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/69.0.3497.100 Safari\/537.36","version":"13.0.6.1"}```</details>

**Comment by marius-wieschollek** [comment]
Did this happen only the first time or does this happen every time?

I can reproduce the `OC\ForbiddenException: This request is not allowed to access the filesystem` error. It disappears as soon as i go to the app tokens and grant file access to the passwords access token.

**Comment by chrsch** [comment]
For me it happens every time I try to use the passwords app. After logout -> login the files app works again until I open up the password app. This happens for every login cycle for all users of the cloud.

**Comment by chrsch** [comment]
I have to correct myself. For some reason I did not set the file access permission for re-testing. With the permission set the problem is gone.
Edit: For new user accounts the problem persists. So it seems not always to help to just enable file system access. For two accounts the behavior after granting file access is differen. After visiting the Passwords app and switching back to the files app the user is logged out.

**Comment by marius-wieschollek** [comment]
I will change the behavior of passwords to automatically require file system access in the token when Encryption is enabled.

**Comment by marius-wieschollek** [comment]
Update released
